image: concertdaw/alpine-meson:v0.1.0

build:
  before_script:
    - mkdir build
    - meson build -Db_coverage=true
  script:
    - ninja -C build
    - meson test -C build --wrap=valgrind
    - ninja -C build coverage-html
