image: concertdaw/alpine-meson:v0.1.0

build:
  stage: test
  before_script:
    - mkdir build
    - meson build -Db_coverage=true
  script:
    - ninja -C build
    - meson test -C build --wrap=valgrind
    - ninja -C build coverage-html
  artifacts:
    paths:
      - build/meson-logs
    expire_in: 10 days

pages:
  stage: deploy
  dependencies:
    - build
  script:
    mv build/meson-logs/coveragereport/ public/
  artifacts:
    paths:
      - public
    expire_in: 10 days
  only:
    - master
