language: c
sudo: false
addons:
  apt:
    packages:
      - libglib2.0-dev
      - libsndfile-dev
before_install:
 - pip3 install meson ninja
 - mkdir build
 - meson build
install:
 - ninja -C build
script:
 - ninja -C build test
