language: c
sudo: false
addons:
  apt:
    packages:
      - libglib2.0-dev
      - libsndfile-dev
      - lcov
before_install:
 - "travis_retry curl -L
    https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip
    > /tmp/ninja-linux.zip"
 - unzip -d ~/.local/bin /tmp/ninja-linux.zip
 - pyenv shell 3.5
 - pip install meson
 - mkdir build
 - meson build -Db_coverage=true
install:
 - ninja -C build
script:
 - ninja -C build test
 - ninja -C build coverage-html
notifications:
  email: false
  irc:
    channels:
     - "chat.freenode.net#concertdaw"
    on_success: change
    on_failure: change
